Workflow setup
datasciencecampus/gov-uk-rap-materials pull request #5
Opened 2021-12-01 09:16 UTC by JosephCrispell

### Description

Adding in a R based [precommit](https://github.com/lorenzwalthert/precommit) workflow with some additional [generic hooks](https://pre-commit.com/hooks.html). This has involved updating scripts to adhere to [styler](https://cran.r-project.org/web/packages/styler/vignettes/introducing_styler.html) and [lintr](https://cran.r-project.org/web/packages/lintr/readme/README.html).

### Changes

- Added `.pre-commit-config.yaml` precommit workflow
- Updated all scripts to match guidelines
- Added lintr config (`.lintr`) with some bespoke settings

### Installation steps:

1. Install [python3](https://www.python.org/downloads/) and [pip3](https://www.activestate.com/resources/quick-reads/how-to-install-and-use-pip3/)
2. Install python [precommit](https://pre-commit.com/) library with: `pip3 install pre-commit`
3. Install R [precommit](https://github.com/lorenzwalthert/precommit) package in R with: `install.packages("precommit")`
4. Navigate to repo in R and initialise precommit workflow: `precommit::use_precommit()`
5. I manage git through terminal rather than through RStudio

2021-12-01 09:23 UTC, jeroenminderman commented
Thanks @JosephCrispell will have a look later today!

2021-12-03 10:55 UTC, jeroenminderman reviewed
Hi @JosephCrispell , I've made a start at looking through this. It all looks good technically, but I unfortunately cannot get this to work on my ONS machine. I believe this is related again to the issues I had setting up precommit at all on the ONS machine, and issues to do with renv and attempted package retrievals when trying to run precommits. I will try to test on my personal machine, to see if I can separate to what extent this is a single-setup issue or a wider ONS network issue. Apologies for the delay!

2021-12-03 11:50 UTC, jeroenminderman commented on CreatingAGantt/CreateGanttChart_18-05-20.R
> +) # Unfortunately self-contained doesn't work
Just a comment and not an issue - this is interesting, was this an automatic edit? Stylewise I agree with most of it, apart from perhaps the lack of an indent on L47-48 (it's part of the `saveWidget()` call?)

2021-12-03 11:55 UTC, jeroenminderman commented on DashboardDemos/InteractiveDashboardWithRShiny_03-09-20.Rmd
> +- [Troubleshooting with stackoverflow](https://stackoverflow.com/questions/tagged/r)
Again a comment unrelated to the `precommit` workflow _per se_, am I right in thinking this file is pretty much the same as `DashboardDemos/InteractiveDashboard_01-09-20.Rmd`? I.e. also using `flexdashboard` as opposed the the traditional Shiny layout?

2021-12-03 15:49 UTC, jeroenminderman commented on .pre-commit-config.yaml
> +    -   id: spell-check
I found that in my (working, personal) set up, the precommit spell checker and secrets checker fails when it needs to check (knitted) html and docx files. Does these pass for you @JosephCrispell? The only way to "make" precommit pass in my case was to add explicit exclusions for (knitted) .html and .docx files. I will push some edits to the branch to show what I did. 
I *think* including .html and .docx in this case as explicit exclusions is OK, because (1) we probably don't need extra spellchecks by `precommit` on docs that were knitted from an Rmd, which would have already been checked for errors - same with knitted htmls. Similarly, any stray secrets in a knitted html would have been present in the source Rmd?

2021-12-03 16:03 UTC, jeroenminderman requested changes
Hi @JosephCrispell This all looks great! I had to test this on my personal laptop as my precommit set up on the ONS laptop still appears to be broken (it would be great to get someone else to check with an ONS machine, just to make sure it isn't just me!).
My only suggestion on the precommit workflow is to add explicit exclusions to the spellchecker and secrets checker for html and docx files - in my case, precommit would fail on knitted HTML files. I don't know why, but do we need spell- and secret checks for HTML and docx files when these have been knitted from Rmd's? I can push the suggested changes to this branch, if that's helpful? (I'm unsure whether this merge request is closed when I submit the review?)

2021-12-03 16:11 UTC, jeroenminderman commented
@JosephCrispell have a look at e30ad3c, we can discuss on Monday

2021-12-06 09:09 UTC, JosephCrispell commented on CreatingAGantt/CreateGanttChart_18-05-20.R
> +) # Unfortunately self-contained doesn't work
Agreed, that's styler working it's magic - going to go back in and add some indents now. Good catch! 🎣

2021-12-06 09:15 UTC, JosephCrispell commented on DashboardDemos/InteractiveDashboardWithRShiny_03-09-20.Rmd
> +- [Troubleshooting with stackoverflow](https://stackoverflow.com/questions/tagged/r)
Yup, it's flexdashboard and shiny. I haven't used the traditional Shiny layouts before - it would be good to edit this script to not rely on flexdashboard - Added as an issue just now

2021-12-06 09:18 UTC, JosephCrispell commented on .pre-commit-config.yaml
> +    -   id: spell-check
Completely agreed, doesn't make sense to spell check `Rmd` outputs alongside original scripts so thanks for editing the exclusions - not quite sure why this didn't throw any errors when I was running 🤔

2021-12-06 09:20 UTC, JosephCrispell commented
Hi @jeroenminderman,

Thanks so much for reviewing the codebase and checking out the new workflow. I am really pleased with it and it was easy to set up (although painful to get passed all the hooks). In return, I'm going to test getting it to work on my ONS laptop and then get back to you - it would be really useful to get this sorted and then feed our learning into the GitHub training materials.

Thanks again!

Joe

2021-12-06 10:44 UTC, jeroenminderman commented
Thanks @JosephCrispell and no problem at all. It's a great repo this and I'm hoping to use material from this in some training for NISR (which would be useful to discuss at some point, separately).
As for the merge request - should we just go ahead with this now or wait until you've had a go on your ONS machine? Note I still don't have it working on mine. The trouble on my end is evidently ONS setup specific though; I *think* it's to do with some of `precommit`'s functionality attempting involves running an `renv`, which then tries to pull package updates from CRAN, which is blocked. But I'm not sure.

2021-12-06 12:48 UTC, JosephCrispell commented
Hi @jeroenminderman,

I think we can merge this pull request and I've created an issue for testing on ONS infrastructure where we can continue the conversation - outputs of this will be more directly relevant to the [ONS GitHub guidance](https://github.com/datasciencecampus/DSCA_GitHub_Training) than the resources in this repo.

Thanks again for taking a look at the code!
Joe

2021-12-20 14:16 UTC, merged